# Generated by Django 3.1.2 on 2021-12-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211219_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_anwser', models.CharField(max_length=350)),
            ],
        ),
        migrations.AlterField(
            model_name='quizarchive',
            name='correct_anwser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.correctanswer'),
        ),
    ]
