# Generated by Django 3.1.2 on 2021-12-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211219_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizarchive',
            name='correct_anwser',
        ),
        migrations.DeleteModel(
            name='CorrectAnswer',
        ),
    ]
